### PR TITLE
add a header to any file touched by module sync

### PR DESCRIPTION
**Pull request by tphoney**

### CODE REVIEW

**Comment by mcanevet** [comment]
@tphoney what about files types that does not support `#` as commented lines marker?

**Comment by tphoney** [comment]
Any feedback is welcome, not sure if this should be a constant, or optional? 
@mcanevet  thanks for the feedback, i will have a think. There could be a list of files that are exceptions ?

**Comment by ferventcoder** [comment]
@mcanevet that's exactly what I was wondering. :)

**Comment by tphoney** [comment]
@mcanevet @ferventcoder in config_defaults.yml we could have a key of header, which would allow you to disable the header eg:

Gemfile:
  header: false 
    ':development, :unit_tests':
....

**Comment by ferventcoder** [comment]
That kind of defeats the purpose though IMHO. I want to know about everywhere that goes and a header should support the comment based on the place it is going's proper comment. Perhaps a property bag for those files that don't use `#`?

**Comment by ferventcoder** [comment]
Updated my previous comment to clarify what I was saying :)

**Comment by tphoney** [comment]
Yeah, where would you suggest that property bag live, would that be in modulesync as a constant, or in the modulesync_config ? @ferventcoder

**Comment by ferventcoder** [comment]
I think both locations. I think there are some that are known that would be here, but I think it should be able to be overridden in modulesync_config.

**Comment by ferventcoder** [comment]
Just as we have the ability to override things all the way down to the module, maybe even it goes down further if that modulesync_config wants it to.

**Comment by tphoney** [comment]
@ferventcoder do we want the ability to specify the comment symbol '#' or just have file_types that are ignored

**Comment by ferventcoder** [comment]
I think in a header text, you would leave out the comment symbol and then another operation uses that comment symbol when it combines it to the files. And it looks at the property bag and the file type to see if it should change the symbol from a default of `#`. Thoughts?

**Comment by tphoney** [comment]
So a user would be able to specify if a file type should have a different symbol. 

*.cnf   = '+'
*.java  = '='

What file  you expect the property bag to live in ?

**Comment by ferventcoder** [comment]
> What file you expect the property bag to live in ?

No idea. That's up for determination. :)

**Comment by tphoney** [comment]
i will make some changes tomorrow, and push it up. thanks for the feedback

**Comment by tphoney** [comment]
So after a long conversation with @DavidS we decided that solving this programmatically does not make sense. There are too many edge cases, no header / custom header / custom symbol / file types.
The easiest solution is to manually put a header this into https://github.com/puppetlabs/modulesync_configs for each file.
I will create a PR for the rubocop fixes that i uncovered.

**Pull request closed without merging**
