### PR TITLE
Using a regex to fix #83

### LINKED ISSUE #83: Update stops on first
We have a makefile (attached) that runs msync to test and then update our puppet modules.  The test seems to be fine, but we just made a change to managed_modules.yml to add a new module, everything else was already synced, and when we try to run msync update it stops when the first module shows no change.

```
$ make
rm -rf modules/*
mkdir -p modules/
bundle install --binstubs=./bin --path=.gem/
Using CFPropertyList (2.2.8) 
Using unf_ext (0.0.7.2) 
Using unf (0.1.4) 
Using domain_name (0.5.20160615) 
Using facter (2.4.6) 
Using git (1.3.0) 
Using json_pure (2.0.1) 
Using hiera (3.2.0) 
Using http-cookie (1.0.2) 
Using mime-types (2.99.2) 
Using puppet (4.5.3) 
Using netrc (0.11.0) 
Using rest-client (1.8.0) 
Using puppet-blacksmith (3.4.0) 
Using modulesync (0.6.1) 
Using bundler (1.3.5) 
Your bundle is complete!
It was installed into ./.gem
./bin/msync update -m "Resync from e73e8407c727754122a4fb797a10ec2969ca97ea of modulesync_config repo"
Syncing puppet-builder
Cloning repository fresh
Cloning from git@github.com:gregswift/puppet-builder.git
No config file under ./modules/puppet-builder/.sync.yml found, using default values
git '--git-dir=/var/lib/jenkins/workspace/pr-builder-modulesync_config/modules/puppet-builder/.git' '--work-tree=/var/lib/jenkins/workspace/pr-builder-modulesync_config/modules/puppet-builder' commit '--message=Resync from e73e8407c727754122a4fb797a10ec2969ca97ea of modulesync_config repo'  2>&1:# On branch master
nothing to commit (working directory clean)
$
```
I would have expected this to move on to the next modules. Instead it just stopped, with no error exit code.

When we run it with noop it acts as expected (I added --noop to the file):
```
$ make
rm -rf modules/*
mkdir -p modules/
bundle install --binstubs=./bin --path=.gem/
Using CFPropertyList (2.2.8) 
Using unf_ext (0.0.7.2) 
Using unf (0.1.4) 
Using domain_name (0.5.20160615) 
Using facter (2.4.6) 
Using git (1.3.0) 
Using json_pure (2.0.1) 
Using hiera (3.2.0) 
Using http-cookie (1.0.2) 
Using mime-types (2.99.2) 
Using puppet (4.5.3) 
Using netrc (0.11.0) 
Using rest-client (1.8.0) 
Using puppet-blacksmith (3.4.0) 
Using modulesync (0.6.1) 
Using bundler (1.3.5) 
Your bundle is complete!
It was installed into ./.gem
./bin/msync update -m "Resync from cbe327420755a661e712a649b7bc5e30f6ffd0c3 of modulesync_config repo" --noop
Syncing puppet-builder
Cloning repository fresh
Cloning from git@github.com:gregswift/puppet-builder.git
No config file under ./modules/puppet-builder/.sync.yml found, using default values
Using no-op. Files in puppet-builder may be changed but will not be committed.
Files changed: 
Files added: 


--------------------------------
Syncing puppet-crmapi
Cloning repository fresh
Cloning from git@github.com:gregswift/puppet-api.git
No config file under ./modules/puppet-api/.sync.yml found, using default values
Using no-op. Files in puppet-crmapi may be changed but will not be committed.
Files changed: 
Files added: 
...snip as it just repeats for each module...
```

And so that looks fine
[Makefile.txt](https://github.com/voxpupuli/modulesync/files/384859/Makefile.txt)

### PR DESCRIPTION
**Pull request by danzilio**
The "working directory clean" message is more specific than "nothing to commit" anyway.

### CODE REVIEW

**Comment by rnelson0** [comment]
Needs to pin json_pure to `~>1.0` for the test to pass. 

The `working directory clean` message, while more specific, does seem to rule out git shipped with EL6 from working, whereas `nothing to commit` appears to work with old and new git. It would be nice if git appeared to commit (ba dum bum) to a standard format for that message, as there are some `no ... to commit` messages as well!

**Comment by danzilio** [comment]
CentOS 7:
```
git version 1.8.3.1
Cloning into 'modulesync'...
# On branch master
nothing to commit, working directory clean
```

CentOS 6:
```
git version 1.7.1
Initialized empty Git repository in /modulesync/.git/
# On branch master
nothing to commit (working directory clean)
```

This regex should match both...

**Comment by danzilio** [comment]
Also, do we even want to bother with Ruby `1.9` support?

**Comment by danzilio** [comment]
Oh jeez...they changed it somewhere in 2.9...

```
git version 2.9.2
Cloning into 'modulesync'...
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working tree clean
```

I'll update the regex...

**Comment by bastelfreak** [comment]
In my opinion we should drop Ruby1.9 and instead add Ruby2.3.1. 1.9 is really EOL since a very long time.

**Comment by rnelson0** [comment]
Heh, I had it backwards, it's the really new one!

To drop Ruby support, I suggest we release a MINOR announcing the deprecation, then a new MAJOR without the support (and with the Ruby version specified in the gemspec).

**Pull request merged**
