### PR TITLE
Exit 1 if git push fails

### PR DESCRIPTION
**Pull request by sean797**
https://github.com/voxpupuli/modulesync/issues/124

### CODE REVIEW

**Comment by rnelson0** [comment]
@sean797 we should have a test for the exit code as well, to prevent regressions, could you add one?

**Comment by sean797** [comment]
Thanks @rnelson0 ! Updated and Travis seems happy 👍

**Comment by rnelson0** [comment]
@sean797 No, thank YOU! :D

**Comment by cdenneen** [comment]
@rnelson0 can we get a new release?

**Comment by sean797** [comment]
@rnelson0 I too would appreciate a new release soon, is there plans to do one?

**Comment by rnelson0** [comment]
See #128 please

**Pull request merged**
