### PR TITLE
issues-122 Sync files that do not conform to *.erb

### PR DESCRIPTION
**Pull request by tphoney**

### CODE REVIEW

**Comment by tphoney** [comment]
This will resolve #122

**Comment by tphoney** [comment]
@DavidS can you have a look

**Comment by ekohl** [comment]
If you support both, would it make sense to only consider files with.```.erb``` extensions templates?

**Comment by DavidS** [comment]
@ekohl that was the goal of my original change. Between push-back from others against that, and this bug here, we're not there yet.

**Comment by tphoney** [comment]
@ekohl @DavidS does this go any further to address your concerns.

**Comment by ekohl** [comment]
I wonder if this should directly implement the non-templated part. I'm afraid the partial implementation might cause confusion.

**Comment by alexjfisher** [comment]
@ghoneycutt I’ve noticed you’ve approved this PR, but since it’s been a year, I’d like to get feedback from @ekohl and @tphoney before merging.

**Pull request closed without merging**
