### PR TITLE
Add -x to skip specified repositories

### PR DESCRIPTION
**Pull request by DavidS**
This can be useful to avoid snowflakes.

### CODE REVIEW

**Comment by bmjen** [comment]
👍

**Comment by rnelson0** [comment]
I do like this feature! However, would -x or -e be a better flag? -v matches the grep flag but I think more users expect it to mean verbose these days.

**Comment by alexjfisher** [comment]
Other than perhaps the choice of `-v`, LGTM.  The relevant tests pass.  Build is failing due to unrelated rubocop failures.

eg
```
lib/modulesync.rb:93:5: C: Block has too many lines. [40/25]
```
Probably best if these are fixed in a separate PR though.  The `managed_modules.each` block probably *is* too complicated, so I guess it's better not to disable the cop.

**Comment by bastelfreak** [comment]
thanks @DavidS !

**Pull request merged**
